### ISSUE TITLE
Improvement: Add Android, iOS, Linux, Windows, MacOS tags

### ISSUE THREAD

**Issue by BenelliFurtado** [chan150/nrf_ble_dfu#1]
Hi, 

this library looks promising, thank you for that! 

Though on pubdev the package does not show if one filters by either of the platforms:

![Screenshot 2024-05-02 at 10 53 59](https://github.com/chan150/nrf_ble_dfu/assets/55577810/3f618f9b-4f45-4d5e-a6b4-eba7a7a507f8)

Maybe you are already aware of this :)

**Comment by chan150** [comment]
Thank you for your comment.
I released `0.0.8` for applying platforms specified.
